# -*- coding: utf-8 -*-
"""TASK1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12TUTFL42CBF9jALSmKaK67FDfpM7j83f

# **THE SPARKS FOUNDATION -DATA SCIENCE AND BUISNESS  ANALYTICS INTERNSHIP**

# **TASK 1-Prediction using Supervised Machine learning**

In this task it is required to predict marks scored by the student basend on no of hours he/she studied.

## ***NAME:PRAKRUTHI H.R***
"""

#importing all required libraries

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

"""#Reading data using pandas
PANDAS IS USED AS DATA ANALYSIS LIBRARY



   



"""

#Reading the data using pandas 
link="https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv"
data=pd.read_csv(link)
print("sucessfully, read the data")

#DATA ANALYSIS
data.head()                   #head returns first  5rows of a dataframe

data.tail()                  #tail returns the last 5 rows of a dataframe

data.info()

#To find number of rows and column
data.shape                # THERE ARE 25 ROWS  AND 2COLUMS IN THIS DATAFRAME

#DESCRIBE() IS USED TO FIND A BASIC STATASTICAL DETAILS
data.describe()

#TO count no of non-NA observation
data.count()

"""# **Visualizing data**"""

# TO FIND RELATION BETWEEN TWO VARIABLES
#PLOTTING THE DATA USING MATPLOTLIB
scores=data['Scores']
hrs=data['Hours']
plt.scatter(hrs,scores,s=None,c='green',marker=None)
plt.grid()
plt.xlabel("Hours studied",fontsize=14)
plt.ylabel("student score",fontsize=14)
plt.title("Hours studied vs Marks scored",fontsize=20)
plt.show()
print("THIS GRAPH SHOWS THERE IS LINEAR RELATIONSHIP BETWEEN TWO VARIABLES")

#To find the corellation between two variables
data.corr()

"""# **TRAINING AND TESTING THE DATA**"""

#HERE LET US SPLIT THE DATASET INTO TWO PARTS:TRAINING DATA AND TESTING DATA

x=data.iloc[:,:-1].values
y= data.iloc[:,1:].values
print("x values:\n",x)
print("y values:\n",y)

#SPLITING DATSET USING train_test_split from sklearn 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=10,test_size=0.3)

"""# **TRAINING THE MODEL**"""

#USING LINEAR REGRESSION
#regression line on training data
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)
plt.scatter(x_train,y_train,c='green') 
plt.plot(x_train,reg.predict(x_train),c='red')
plt.title("regression line on train dataset",fontsize=16)
plt.xlabel("Hours studied",fontsize=14)
plt.ylabel("student scores",fontsize=14)
plt.xticks()
plt.yticks()
plt.grid()
plt.show()

#regression line on test dataset
reg.fit(x_test,y_test)
plt.scatter(x_test,y_test,c='green')
plt.plot(x_test,reg.predict(x_test),c='red')
plt.xlabel("Hours studied",fontsize=14)
plt.ylabel("student score",fontsize=14)
plt.title("regression line on test dataset",fontsize=16)
plt.grid()
plt.xticks()
plt.yticks()
plt.show()

"""# **Making predictions**"""

from sklearn.metrics import mean_absolute_error
y_predict=reg.predict(x_test)
d={'ACTUAL':[y_test],'predicted':[y_predict]}
df=pd.DataFrame(d)
df

"""## ***predecting  student score if he/she studies for 9.25 hours ***"""

hrs=float(input())
predict=reg.predict([[hrs]])[0]

print("The predicted score if he/she studies for",hrs,":",predict)

"""### ***if a person studies for 9.25 hrs he/she scores 85.22 ***"""

from sklearn.metrics import mean_absolute_error,mean_squared_error    # lower the error higher the accuracy
print("mean absolute error:",mean_absolute_error(y_test,y_predict))
print("root squared error:",np.sqrt(mean_absolute_error(y_test,y_predict)))
print("mean square error:",mean_squared_error(y_test,y_predict))
print("Since,the value of mae,rmse and mse are lower the regression model is more accurate")

"""# **THANK YOU**"""